# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usergroup', models.CharField(choices=[('0', '\u672a\u5206\u914d'), ('1', '\u5b66\u751f'), ('2', '\u8001\u5e08'), ('3', '\u9886\u5bfc')], default='0', max_length=1, verbose_name='\u7fa4\u7ec4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
