# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20170729_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(max_length=32),
        ),
    ]
