# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_auto_20170730_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=' ', max_length=150, unique=True),
        ),
    ]
