# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPush', '0010_newspost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.CharField(default=b'objects', max_length=50, verbose_name='\u4f5c\u8005'),
        ),
    ]
