# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPush', '0012_auto_20170723_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.CharField(default=' ', max_length=50, verbose_name='\u4f5c\u8005'),
        ),
    ]
